name: OpenVVC CI
on: [push, pull_request]
jobs:
  Generic:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependency
        if: matrix.os == 'macos-latest'
        run: |
          brew install autoconf automake libtool
      - name: Autoconf
        run: autoreconf -if
      - name: Configure
        run: ./configure
      - name: Compilation
        run: make
      - name: Download Streams
        run: ./CI/dlvideobin https://nasext-vaader.insa-rennes.fr/ietr-vaader/OVVC/conf_stream/ ./CI/test_bitstreams/conf_stream/ --no_md5
      - name: Set Env Variables 
        run: export OVDEC=$(pwd)/examples/dectest
      - name: Non regression testing
        run: OVDEC=./examples/dectest OVSTREAM=./CI/test_bitstreams ./CI/ovnreg ./CI/conf.vmd5 --no_cleanup --keep_fail
